-- local fugitive_opts = {noremap = true, silent = true};
-- vim.api.nvim_buf_set_keymap(0, 'n', 'cc', '<cmd>Git commit --quiet<CR>', fugitive_opts)
-- vim.api.nvim_buf_set_keymap(0, 'n', 'ca', '<cmd>Git commit --quiet --amend<CR>', fugitive_opts)
-- vim.api.nvim_buf_set_keymap(0, 'n', 'ce', '<cmd>Git commit --quiet --amend --no-edit<CR>', fugitive_opts)
--
