local keymaps = {
  {'n','<leader>ve', '<cmd>e $MYVIMRC<cr>'},
  {'n','<leader>w', '<cmd>w<cr>'},
  {'n','<leader>q', '<cmd>q<cr>'},
  {'n','<leader>=', '<C-w>='},
  {'n','<C-j>', '<C-w><C-j>'},
  {'n','<C-k>', '<C-w><C-k>'},
  {'n','<C-h>', '<C-w><C-h>'},
  {'n','<C-l>', '<C-w><C-l>'},
  {'n','y%', '<cmd>let @+=@%<cr>'},
  {'n','<F12>', '<cmd>ccl<cr>'},
  {'n','<down>', '<cmd>cn<cr>'},
  {'n','<up>', '<cmd>cp<cr>'},
  {'n','Q', '<Nop>'},
  {'n','<f1>', '<cmd>RnvimrToggle<cr>'},
  {'t','<leader><f1>', '<C-\\><C-n>:RnvimrResize<cr>'},
  {'n','<f4>', '<cmd>lua require(\'telescope.builtin\').live_grep()<cr>'},
  {'n','<leader><f4>', '<cmd>lua require(\'telescope.builtin\').grep_string({search = vim.fn.expand("<cword>")})<cr>'},
  {'n','<leader>a', '<cmd>lua require(\'telescope.builtin\').git_branches()<cr>'},
  {'n','<leader>b', '<cmd>lua require(\'telescope.builtin\').buffers()<cr>'},
  {'n','<leader>o', '<cmd>lua require(\'telescope.builtin\').lsp_document_symbols()<cr>'},
  {'n','<leader>O', '<cmd>lua require(\'telescope.builtin\').lsp_workspace_symbols()<cr>'},
  {'n','<leader>f', '<cmd>lua telescope_smart_files()<cr>'},
  {'n','<leader>F', '<cmd>lua require(\'telescope\').extensions.frecency.frecency()<cr>'},
  {'n','<leader>s', '<cmd>G<cr>'},
  {'n','<leader>gp', '<cmd>G push<cr>' },
  {'n','<leader>gf', '<cmd>G fetch<cr>'},
  {'n','<leader>gl', '<cmd>G pull<cr>'},
  {'n','<leader>2', '<cmd>diffget //2<cr>'},
  {'n','<leader>3', '<cmd>diffget //3<cr>'},
  {'n','<leader>pb', ':G checkout --quiet <C-r>+<cr>'},
  {'n','<leader>go', '<cmd>GV<cr>'},
  {'n','<leader>g%', '<cmd>GV!<cr>'},
  {'n','<leader>gcb', ':G checkout origin/develop -b' },
  {'n','<leader>gw', '<cmd>lua require(\'telescope\').extensions.git_worktree.git_worktrees()<cr>' },
  {'n','<leader>0', 'mF:%!eslint_d --stdin --fix-to-stdout --stdin-filename %<CR>`F'},
  {'n','<leader>x', '<cmd>x<cr>'},
  {'n','<leader>y', '"+y'},
  {'v','<leader>y', '"+y'},
  {'n','<leader>p', '"+p'},
  {'v','<leader>p', '"+p'},
  {'n','<leader>Y', 'gg"+yG'},
  {'i','<silent><expr> <C-e>', 'compe#close(\'<C-e>\')'},
  {'n','<leader>db', '<cmd>lua require\'dap\'.toggle_breakpoint()<cr>'},
  {'n','<leader>dl', '<cmd>lua require\'dap\'.continue()<cr>'},
  {'n','<leader>ll', ':lua vim.lsp.stop_client(vim.lsp.get_active_clients())<cr>:edit<cr>'},
  {'n','gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>'},
  {'n','gd', '<Cmd>lua vim.lsp.buf.definition()<CR>'},
  {'n','K', '<cmd>lua vim.lsp.buf.hover()<CR>'},
  {'n','gi', '<cmd>lua vim.lsp.buf.implementation()<CR>'},
  {'n','<C-s>', '<cmd>lua vim.lsp.buf.signature_help()<CR>'},
  {'n','<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>'},
  {'n','<f2>', '<cmd>lua vim.lsp.buf.rename()<CR>'},
  {'n','gr', '<cmd>lua vim.lsp.buf.references()<CR>'},
  {'n','<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>'},
  {'n','[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>'},
  {'n',']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>'},
  {'n','<space>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>'},
  --{'n','<leader>x', '<cmd>lua vim.lsp.buf.formatting()<CR>'},
}

for _,mymap in pairs(keymaps) do
  Keymap(mymap[1], mymap[2], mymap[3])
end

vim.api.nvim_set_keymap( 'i', '<C-Space>', "compe#complete()", {noremap = true, expr = true, silent = true})

